name: allen-institute-sandbox
channels:
  - defaults
  - conda-forge
  - simpleitk
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scikit-image
  - beautifulsoup4
  - scipy
  - simpleitk
  - matplotlib
  - jupyter
  - jupyterlab
  - pyspark
  - ipykernel
  - ipywidgets
  - boto3
  - hdmf
  - pip:
    - opencv-python
    - allensdk
    - pynwb
    - nwbwidgets
    
  
  